version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd server
      - npm install
      - cd ../client
      - npm install
  build:
    commands:
      - echo Building the server...
      - cd ../server
      - npm run build
      - echo Building the client...
      - cd ../client
      - npm run build
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - server/**/*
    - client/build/**/*
  discard-paths: no